"use client";

import { FormEvent, useEffect, useState } from "react";

type PageKey = "home" | "social" | "education" | "health" | "investment" | "culture" | "membership" | "contact";

const routeMap: Record<string, PageKey> = {
  home: "home", social: "social", education: "education", health: "health",
  investment: "investment", culture: "culture", membership: "membership", contact: "contact",
};

const pageInfo: Record<Exclude<PageKey, "home" | "membership" | "contact">, { title: string; accent: string; lead: string; icon: string; services: string[]; stats: [string, string][] }> = {
  social: { title: "الخدمات الاجتماعية", accent: "معاً.. نرعى ونساند", lead: "برامج ومبادرات اجتماعية وإنسانية تهدف إلى دعم أبناء الولاية وتحقيق مجتمع متماسك ومتكافل.", icon: "♡", services: ["تواصل مباشر", "حالات إنسانية", "استشارة اجتماعية", "برامج ومبادرات", "دعم المحتاجين"], stats: [["12,680+", "مستفيد"], ["3,250+", "أسرة مستفيدة"], ["1,850+", "حالة إنسانية"], ["650+", "فرصة دعم"]] },
  education: { title: "التعليم", accent: "استثمار في المستقبل", lead: "بيئة تعليمية رقمية متكاملة تدعم الطلاب والمعلمين وتوفر محتوى تعليمياً متطوراً يواكب احتياجات المستقبل.", icon: "✦", services: ["الفصول الافتراضية", "الواجبات المدرسية", "المحتوى التفاعلي", "التقييم والنتائج", "المنح الدراسية"], stats: [["12,680", "طالب وطالبة"], ["65", "معلماً ومعلمة"], ["156", "مادة افتراضية"], ["420", "دورة تدريبية"]] },
  health: { title: "الصحة", accent: "صحتك تهمنا.. وجودة حياتك هدفنا", lead: "خدمات صحية رقمية متكاملة تصل إليك أينما كنت، بسهولة وخصوصية وأمان.", icon: "+", services: ["التأمين الطبي", "الاستشارات الطبية", "العيادة الإلكترونية", "الصيدلية الخيرية", "طلب مساعدة"], stats: [["24/7", "خدمة مستمرة"], ["40+", "طبيباً معتمداً"], ["12", "تخصصاً طبياً"], ["98%", "رضا المستفيدين"]] },
  investment: { title: "الاستثمار في ولاية نهر النيل", accent: "فرص واعدة.. مستقبل مستدام", lead: "بيئة استثمارية جاذبة وموارد طبيعية غنية وموقع استراتيجي يدعم التنمية ويحقق عوائد مجزية للمستثمرين.", icon: "↗", services: ["الزراعة والإنتاج النباتي", "الثروة الحيوانية", "الصناعة التحويلية", "التعدين والمحاجر", "السياحة والضيافة"], stats: [["2.9 مليون+", "هكتار زراعي"], ["500 ألف", "هكتار مروي"], ["11+", "مجمعاً صناعياً"], ["850 كم", "من نهر النيل"]] },
  culture: { title: "الثقافة", accent: "هوية وإبداع.. نصون تراثنا", lead: "منصة ثقافية رقمية تساهم في إبراز التراث السوداني الأصيل ودعم المواهب والإبداع في جميع المجالات.", icon: "◈", services: ["الفعاليات والأنشطة", "الأخبار الثقافية", "المكتبة الرقمية", "الفنون والأدب", "التراث والتاريخ"], stats: [["35", "فرقة وجمعية"], ["650+", "عضو فني"], ["120", "مبادرة ثقافية"], ["85", "فعالية ثقافية"]] },
};

const cards: Record<string, { icon: string; title: string; text: string }[]> = {
  social: [{icon:"☏",title:"تواصل مباشر",text:"فريق الدعم الاجتماعي جاهز لخدمتك"},{icon:"⌂",title:"حالات إنسانية",text:"متابعة الحالات وتقديم الدعم اللازم"},{icon:"◌",title:"استشارة اجتماعية",text:"استشارات بسرية وخصوصية"},{icon:"♧",title:"برامج ومبادرات",text:"مبادرات مجتمعية متنوعة"}],
  education: [{icon:"▣",title:"الفصول الافتراضية",text:"حصص مباشرة وتسجيلات تعليمية"},{icon:"▤",title:"المواد الدراسية",text:"كتب وملخصات وتمارين"},{icon:"✓",title:"الاختبارات",text:"اختبارات دورية وتقارير أداء"},{icon:"★",title:"دورات تقوية",text:"مسارات مناسبة لكل مرحلة"}],
  health: [{icon:"♢",title:"التأمين الطبي",text:"خطط مرنة وتغطية موثوقة"},{icon:"☏",title:"الاستشارات الطبية",text:"استشر طبيباً من أي مكان"},{icon:"▦",title:"العيادة الإلكترونية",text:"مواعيد ومتابعة دورية"},{icon:"+",title:"الصيدلية الخيرية",text:"دواء آمن للأسر المحتاجة"}],
  investment: [{icon:"❧",title:"الزراعة",text:"أراضٍ خصبة وموارد مائية"},{icon:"♜",title:"الصناعة",text:"مناطق صناعية واعدة"},{icon:"◆",title:"التعدين",text:"موارد طبيعية متنوعة"},{icon:"⌁",title:"السياحة",text:"وجهات نيلية وتاريخية"}],
  culture: [{icon:"♪",title:"ليالي النيل",text:"مهرجانات وعروض تراثية"},{icon:"▥",title:"المعارض",text:"تجارب فنية ملهمة"},{icon:"✎",title:"المكتبة الرقمية",text:"كتب ومراجع سودانية"},{icon:"◉",title:"صنّاع الثقافة",text:"منصة للمواهب والإبداع"}],
};

const nav = [["/", "الرئيسية"], ["/membership", "عن الرابطة"], ["/social", "الخدمات"], ["/investment", "المبادرات"], ["/culture", "الثقافة"], ["/education", "التعليم"], ["/contact", "تواصل معنا"]];

function Logo() { return <a className="logo" href="/"><span className="logo-mark"><i /></span><b>رابطة ولاية نهر النيل<em>الرقمية</em></b></a>; }

function Header({ active }: { active: PageKey }) {
  const [open, setOpen] = useState(false);
  return <header className="header"><div className="nav-wrap"><Logo/><nav className={open ? "open" : ""}>{nav.map(([href,label]) => <a key={href} className={(active === "home" && href === "/") || href.includes(active) ? "active" : ""} href={href}>{label}</a>)}</nav><div className="nav-actions"><a className="search" href="/contact" aria-label="بحث">⌕</a><a className="button small" href="/membership">تسجيل الدخول</a><button className="menu" onClick={() => setOpen(!open)} aria-label="فتح القائمة">{open ? "×" : "☰"}</button></div></div></header>;
}

function Footer() { return <footer><div className="footer-grid"><div><Logo/><p>منصة رقمية شاملة لخدمة أبناء ولاية نهر النيل في الداخل والخارج.</p></div><div><h4>روابط سريعة</h4><a href="/">الرئيسية</a><a href="/membership">عن الرابطة</a><a href="/contact">تواصل معنا</a></div><div><h4>خدمات الرابطة</h4><a href="/education">التعليم</a><a href="/health">الصحة</a><a href="/investment">الاستثمار</a></div><div><h4>تواصل معنا</h4><p>+249 912 345 678</p><p>info@nilenile.org</p><p>ولاية نهر النيل - السودان</p></div></div><div className="copyright">جميع الحقوق محفوظة © 2026 · رابطة ولاية نهر النيل الرقمية <span>◉ ◉ ◉ ◉</span></div></footer> }

function Reveal() { useEffect(() => { const obs = new IntersectionObserver(es => es.forEach(e => e.isIntersecting && e.target.classList.add("seen")), {threshold:.12}); document.querySelectorAll(".reveal").forEach(el => obs.observe(el)); return () => obs.disconnect(); }, []); return null; }

function Home() {
  const serviceLinks = [{t:"الثقافة",i:"◈",h:"/culture",c:"teal",x:"التراث والفعاليات والمكتبة"},{t:"التعليم",i:"✦",h:"/education",c:"blue",x:"مدرسة النيل والمنح والدورات"},{t:"الاستثمار",i:"↗",h:"/investment",c:"orange",x:"الفرص والمشروعات التنموية"},{t:"الصحة",i:"+",h:"/health",c:"red",x:"الاستشارات والتأمين والدواء"},{t:"الخدمات الاجتماعية",i:"♡",h:"/social",c:"green",x:"المساعدة والتكافل المجتمعي"}];
  return <><section className="home-hero"><div className="hero-copy reveal"><span className="eyebrow">رابطة رقمية · مجتمع واحد</span><h1>رابطة ولاية<br/><em>نهر النيل الرقمية</em></h1><p>منصة رقمية شاملة تربط أبناء ولاية نهر النيل في الداخل والخارج، وتجمع الخدمات والمبادرات والفرص في مكان واحد.</p><div className="hero-actions"><a className="button" href="#services">استكشف المنصة <b>←</b></a><a className="button ghost" href="/membership">تعرّف على عضويتنا</a></div></div><div className="river-art reveal"><div className="sun"/><div className="river"/><div className="bridge"/><div className="float-card"><b>منصة رقمية واحدة</b><span>لكل أبناء الولاية</span></div></div></section><section className="stats-strip reveal">{[["200+","المبادرات والبرامج"],["35K+","المستفيدون"],["120+","الخدمات المقدمة"],["45+","دولة حول العالم"]].map(x=><div key={x[1]}><b>{x[0]}</b><span>{x[1]}</span></div>)}</section><section className="join reveal"><div className="member-card"><Logo/><b>عضو في رابطة ولاية نهر النيل الرقمية</b><small>0001 · عضوية</small></div><div><span className="eyebrow">انضم الآن</span><h2>كن جزءاً من مجتمعنا الرقمي</h2><p>عضويتك تفتح لك أبواباً للخدمات والبرامج وفرص التواصل والمساهمة.</p></div><a className="button" href="/membership">انضم الآن ←</a></section><section id="services" className="section"><div className="section-title reveal"><span>ابدأ رحلتك من هنا</span><h2>خدماتنا الرقمية</h2></div><div className="service-grid">{serviceLinks.map(s=><a href={s.h} className={`service-card reveal ${s.c}`} key={s.t}><i>{s.i}</i><h3>{s.t}</h3><p>{s.x}</p><span>الدخول للخدمة ←</span></a>)}</div></section><section className="feature-band reveal"><div><span>فرص تصنع المستقبل</span><h2>الاستثمار في ولاية نهر النيل</h2><p>فرص واعدة في القطاعات الزراعية والصناعية والسياحية.</p></div><div className="mini-features"><b>❧ زراعي</b><b>▦ صناعي</b><b>⌂ سكني</b></div><a className="button" href="/investment">استكشف الفرص</a></section><section className="section"><div className="section-title reveal"><span>نتعلم أينما كنا</span><h2>تعليم رقمي يبني الغد</h2></div><div className="split-panels"><article className="big-panel reveal"><div className="panel-art student">✦</div><div><h3>مدرسة نهر النيل الإلكترونية</h3><p>فصول افتراضية، مناهج متكاملة واختبارات تفاعلية لجميع المراحل.</p><a href="/education">الدخول إلى المدرسة ←</a></div></article><article className="big-panel dark reveal"><div className="panel-art">◎</div><div><h3>معهد نهر النيل الإلكتروني</h3><p>تدريب مهني متطور وشهادات احترافية تساعدك على بناء مستقبلك.</p><a href="/education">استكشف البرامج ←</a></div></article></div></section><section className="market reveal"><div className="market-visual">▦<i>●</i><i>●</i><i>●</i></div><div><span className="eyebrow">السوق السوداني الإلكتروني</span><h2>منتجات سودانية تصل إليك</h2><p>منصة آمنة تجمع المنتجات والخدمات السودانية وتدعم النشاط المحلي.</p></div><button className="button">تصفح السوق الآن</button></section></>;
}

function ServicePage({ type }: { type: Exclude<PageKey, "home" | "membership" | "contact"> }) {
  const p = pageInfo[type]; const cs = cards[type];
  return <><section className={`inner-hero ${type}`}><div className="hero-copy reveal"><span className="eyebrow">خدمات رابطة نهر النيل</span><h1>{p.title}</h1><h2>{p.accent}</h2><p>{p.lead}</p><a className="button" href="#main-services">استكشف الخدمات ←</a></div><div className="symbol-art reveal"><i>{p.icon}</i><span>{type === "health" ? "رعاية آمنة" : type === "education" ? "معرفة بلا حدود" : type === "investment" ? "نمو مستدام" : type === "culture" ? "تراث وإبداع" : "تكافل ومساندة"}</span></div></section><div className="quick-row reveal">{p.services.map((s,i)=><a href="#main-services" key={s}><b>{["◉","◇","◌","✦","♡"][i]}</b>{s}</a>)}</div><section className="stats-dark reveal">{p.stats.map(([n,l])=><div key={l}><b>{n}</b><span>{l}</span></div>)}</section><section id="main-services" className="section"><div className="section-title reveal"><span>مصممة لتناسب احتياجاتك</span><h2>خدمات {p.title}</h2></div><div className="content-cards">{cs.map((c,i)=><article className="content-card reveal" key={c.title}><div className="card-visual"><b>{c.icon}</b><span>0{i+1}</span></div><h3>{c.title}</h3><p>{c.text}</p><ul><li>تجربة رقمية سهلة وآمنة</li><li>دعم مباشر من فريق متخصص</li><li>متابعة سريعة للطلبات</li></ul><button className="text-button">اعرف المزيد ←</button></article>)}</div></section><section className="section alt"><div className="section-title reveal"><span>نصنع أثراً حقيقياً</span><h2>{type === "investment" ? "فرص استثمارية مميزة" : type === "culture" ? "فعاليات ومبادرات قادمة" : "مبادراتنا الحالية"}</h2></div><div className="initiatives">{[1,2,3].map((n,i)=><article className="initiative reveal" key={n}><span className={`cover cover-${type}`}>{p.icon}</span><div><small>{i === 0 ? "جديد" : "مستمر"}</small><h3>{cs[i]?.title}</h3><p>{cs[i]?.text} عبر منصة الرابطة الرقمية.</p><div className="progress"><i style={{width:`${52+i*17}%`}}/></div><b>{52+i*17}% مكتمل</b></div></article>)}</div></section><section className="cta reveal"><div><span>نحن هنا لخدمتك</span><h2>هل تحتاج مساعدة أو استشارة؟</h2></div><a className="button" href="/contact">تواصل معنا الآن ←</a></section></>;
}

function Membership() { const [selected,setSelected]=useState(1); return <><section className="membership-hero"><div className="hero-copy reveal"><span className="eyebrow">معاً.. نبني المستقبل</span><h1>باقات العضوية</h1><h2>الاشتراكات السنوية</h2><p>اختر الباقة التي تناسبك واستمتع بمزايا حصرية تدعمك وتخدم أبناء ولايتك.</p></div><div className="member-card large reveal"><Logo/><b>عضو في رابطة ولاية نهر النيل الرقمية</b><small>0001 · عضوية</small></div></section><section className="benefits reveal">{[["تواصل", "مجتمع متفاعل"],["أمان","موثوق وآمن"],["مزايا","خدمات حصرية"],["تأثير","مساهمة مؤثرة"]].map(x=><div key={x[0]}><b>◇</b><h3>{x[1]}</h3><span>{x[0]}</span></div>)}</section><section className="section"><div className="section-title reveal"><span>اختر ما يناسبك</span><h2>خطط عضوية مرنة</h2></div><div className="plans">{[{n:"الباقة الأساسية",p:"50",f:["الدخول إلى منصة الرابطة","النشرة الدورية","دعوات عامة للفعاليات"]},{n:"الباقة المميزة",p:"100",f:["كل مزايا الباقة الأساسية","الأولوية في التسجيل","خصومات ومحتوى حصري"]},{n:"الباقة الداعمة",p:"200",f:["كل مزايا الباقات السابقة","دعم مباشر للمشاريع","دعوات VIP للفعاليات"]}].map((x,i)=><article onClick={()=>setSelected(i)} className={`plan reveal ${selected===i?"selected":""}`} key={x.n}>{i===1&&<span className="popular">الأكثر اختياراً</span>}<h3>{x.n}</h3><b>{x.p}<small> ريال / سنوياً</small></b><ul>{x.f.map(f=><li key={f}>✓ {f}</li>)}</ul><button className="button" onClick={()=>document.getElementById("register")?.scrollIntoView({behavior:"smooth"})}>اختر هذه الباقة</button></article>)}</div></section><RegisterForm/></> }

function RegisterForm() { const [done,setDone]=useState(false); const submit=(e:FormEvent)=>{e.preventDefault();setDone(true)}; return <section id="register" className="section alt"><div className="section-title reveal"><span>خطوة واحدة للانضمام</span><h2>نموذج تسجيل العضوية</h2></div>{done?<div className="success"><b>✓</b><h2>تم استلام طلبك بنجاح</h2><p>سيتواصل معك فريق الرابطة لاستكمال إجراءات العضوية.</p></div>:<form className="register-form reveal" onSubmit={submit}><label>الاسم الكامل<input required placeholder="اكتب اسمك الكامل"/></label><label>البريد الإلكتروني<input required type="email" placeholder="name@example.com"/></label><label>رقم الجوال<input required type="tel" placeholder="+249"/></label><label>المدينة<select required defaultValue=""><option value="" disabled>اختر المدينة</option><option>عطبرة</option><option>الدامر</option><option>شندي</option><option>بربر</option></select></label><label>المجال المهني<input placeholder="مجال عملك"/></label><label>الباقة المختارة<select defaultValue="المميزة"><option>الأساسية</option><option>المميزة</option><option>الداعمة</option></select></label><label className="wide check"><input type="checkbox" required/> أوافق على الشروط وسياسة الخصوصية</label><button className="button wide" type="submit">إرسال طلب العضوية ←</button></form>}</section> }

function Contact() { const [sent,setSent]=useState(false); return <><section className="contact-hero"><div className="contact-art reveal"><span>✉</span><b>نحن دائماً بالقرب منك</b></div><div className="hero-copy reveal"><span className="eyebrow">نحن هنا لخدمتكم</span><h1>تواصل معنا</h1><h2>يسعدنا أن نسمع منك</h2><p>نستقبل استفساراتكم ومقترحاتكم وشكاواكم، وفريقنا جاهز للرد وتقديم الدعم في أسرع وقت ممكن.</p></div></section><section className="benefits reveal">{[["☏","فريق متخصص"],["◷","استجابة سريعة"],["♢","خصوصية وأمان"],["◎","خدمتكم أينما كنتم"]].map(x=><div key={x[1]}><b>{x[0]}</b><h3>{x[1]}</h3></div>)}</section><section className="contact-section"><aside className="contact-methods reveal"><h2>طرق التواصل</h2>{[["واتساب","+249 912 345 678"],["اتصال هاتفي","+249 123 456 789"],["البريد الإلكتروني","info@nilenile.org"],["العنوان","ولاية نهر النيل - السودان"],["ساعات العمل","الأحد إلى الخميس · 9ص - 5م"]].map((x,i)=><div key={x[0]}><b>{["◉","☏","✉","⌖","◷"][i]}</b><span><strong>{x[0]}</strong>{x[1]}</span></div>)}</aside><form className="contact-form reveal" onSubmit={e=>{e.preventDefault();setSent(true)}}><h2>أرسل لنا رسالة</h2>{sent?<div className="success"><b>✓</b><h3>وصلت رسالتك</h3><p>شكراً لتواصلك، سنرد عليك قريباً.</p></div>:<><div className="form-row"><label>الاسم الكامل<input required/></label><label>البريد الإلكتروني<input required type="email"/></label></div><label>رقم الجوال<input type="tel"/></label><label>نوع الرسالة<select><option>استفسار عام</option><option>اقتراح</option><option>شكوى</option><option>دعم فني</option></select></label><label>نص الرسالة<textarea required rows={5}/></label><button className="button" type="submit">إرسال الرسالة ←</button></>}</form></section><section className="faq section"><div className="section-title"><span>إجابات سريعة</span><h2>أسئلة شائعة</h2></div><div className="faq-grid">{["كيف أسجل في الرابطة؟","ما هي الخدمات المتاحة؟","كيف أتابع طلبي؟","ما طرق دفع العضوية؟"].map(q=><details key={q}><summary>{q}</summary><p>يمكنك الوصول إلى جميع التفاصيل من خلال المنصة أو التواصل مباشرة مع فريق الدعم.</p></details>)}</div></section></> }

export default function NileSite({ page }: { page: string }) { const active = routeMap[page] || "home"; return <div dir="rtl"><Reveal/><Header active={active}/><main>{active==="home"?<Home/>:active==="membership"?<Membership/>:active==="contact"?<Contact/>:<ServicePage type={active}/>}</main><Footer/></div> }
