"use client";

import { FormEvent, useEffect, useRef, useState } from "react";

type PageKey = "home" | "social" | "education" | "health" | "investment" | "culture" | "membership" | "register" | "photo" | "payment" | "success" | "contact";
type PortalKey = "social" | "education" | "health" | "investment" | "culture";

const routeMap: Record<string, PageKey> = {
  home:"home", social:"social", education:"education", health:"health", investment:"investment", culture:"culture",
  membership:"membership", register:"register", photo:"photo", payment:"payment", success:"success", contact:"contact",
};

const nav = [["/","الرئيسية"],["/membership","عن الرابطة"],["/social","الخدمات"],["/investment","المبادرات"],["/culture","الثقافة"],["/education","التعليم"],["/contact","تواصل معنا"]];

const info: Record<PortalKey, {title:string; accent:string; lead:string; hero:string; icon:string; tabs:string[]; stats:[string,string][]; cards:{title:string;text:string;image?:string;icon:string}[]; section:string}> = {
  social:{title:"الخدمات الاجتماعية",accent:"معاً.. نرعى ونساند",lead:"نقدم برامج ومبادرات اجتماعية وإنسانية تهدف إلى دعم أبناء مجتمعنا في مختلف الظروف، لبناء مجتمع متماسك ومتكافل.",hero:"/assets/social-hero-hq.png",icon:"♡",tabs:["حالات إنسانية","تواصل مباشر","استشارة اجتماعية","برامج ومبادرات","دعم المحتاجين"],stats:[["12,680+","مستفيد من خدماتنا"],["3,250+","أسرة مستفيدة"],["1,850+","حالة إنسانية"],["650+","فرصة دعم"]],section:"مبادراتنا الحالية",cards:[{title:"صندوق العلاج",text:"مساعدة المرضى في تغطية تكاليف العلاج والأدوية",image:"/assets/social-medical-hq.png",icon:"✚"},{title:"مشروع ترميم المنازل",text:"ترميم المنازل المتضررة وتحسين بيئة السكن",image:"/assets/social-renovation-hq.png",icon:"⌂"},{title:"دعم التعليم",text:"دعم الرسوم والاحتياجات التعليمية لأبناء الأسر",image:"/assets/social-education-hq.png",icon:"✦"},{title:"سلة الخير الرمضانية",text:"توزيع سلات غذائية على الأسر المحتاجة",image:"/assets/social-basket-hq.png",icon:"♡"}]},
  education:{title:"التعليم",accent:"استثمار في المستقبل",lead:"نقدم بيئة تعليمية رقمية متكاملة تدعم الطلاب والمعلمين، وتوفر محتوى تعليمياً متطوراً لتلبية احتياجات التعليم في مكان وزمان يناسب الجميع.",hero:"/assets/education-hero-hq.png",icon:"▣",tabs:["مدرسة نهر النيل الإلكترونية","الدورات وكورسات التقوية","المنح الدراسية","المكتبة الرقمية","الاختبارات والامتحانات","النتائج والتقارير","الاستشارات التعليمية","الأخبار والفعاليات التعليمية"],stats:[["12,680","طالب وطالبة"],["65","معلماً ومعلمة"],["156","مادة افتراضية"],["420","دورة تدريبية"]],section:"الدورات وكورسات التقوية",cards:[{title:"إدارة المشاريع",text:"دورة عملية لتطوير المهارات الإدارية",image:"/assets/course-project-hq.png",icon:"◫"},{title:"اللغة الإنجليزية",text:"مسار متدرج لجميع المستويات",image:"/assets/course-english-hq.png",icon:"A"},{title:"تصميم الجرافيك",text:"أساسيات التصميم للمهتمين",image:"/assets/course-design-hq.png",icon:"✎"},{title:"أساسيات البرمجة للمبتدئين",text:"مدخل عملي للعالم الرقمي",image:"/assets/course-code-hq.png",icon:"⌘"}]},
  health:{title:"الصحة",accent:"معاً من أجل صحة أفضل",lead:"خدمات صحية متكاملة لأبناء ولاية نهر النيل في الداخل والخارج، برعاية رابطة الولاية الرقمية.",hero:"/assets/health-hero-hq.png",icon:"✚",tabs:["الاستشارات الطبية","العيادة الإلكترونية","التأمين الطبي","الصيدلية الخيرية","طلب المساعدة والتواصل مع الرابطة"],stats:[["24/7","خدمة مستمرة"],["40+","طبيب معتمد"],["12","تخصصاً طبياً"],["98%","رضا المستفيدين"]],section:"خدماتنا الصحية",cards:[{title:"الاستشارات الطبية",text:"استشارات مع نخبة من الأطباء في مختلف التخصصات",image:"/assets/health-consult-hq.png",icon:"☏"},{title:"العيادة الإلكترونية",text:"استشر الطبيب المناسب عبر الإنترنت من أي مكان",image:"/assets/health-clinic-hq.png",icon:"▣"},{title:"التأمين الطبي",text:"باقات تأمين ميسرة لأعضاء الرابطة وأسرهم",image:"/assets/health-insurance-hq.png",icon:"♢"},{title:"الصيدلية الخيرية",text:"توفير الأدوية للمحتاجين بأسعار رمزية",image:"/assets/health-pharmacy-hq.png",icon:"✚"}]},
  investment:{title:"الاستثمار في ولاية نهر النيل",accent:"فرص واعدة.. مستقبل مستدام",lead:"بيئة استثمارية جاذبة بموارد طبيعية غنية وموقع استراتيجي يدعم التنمية ويحقق عوائد مجزية للمستثمرين.",hero:"/assets/investment-hero-hq.png",icon:"↗",tabs:["فرص الاستثمار","القطاعات الاستثمارية","الحوافز والتسهيلات","دليل المستثمر","قصص نجاح"],stats:[["2.9 مليون+","هكتار زراعي"],["500 ألف","هكتار مروي"],["11+","مجمعات صناعية"],["850 كم","من نهر النيل"]],section:"القطاعات الاستثمارية",cards:[{title:"السياحة والضيافة",text:"مواقع أثرية وطبيعية وفنادق ومنتجعات",image:"/assets/invest-tourism-hq.png",icon:"⌁"},{title:"التعدين والمحاجر",text:"ذهب ومعادن ومحاجر متنوعة",image:"/assets/invest-mining-hq.png",icon:"◆"},{title:"الصناعة التحويلية",text:"مواد غذائية وصناعات هندسية",image:"/assets/invest-industry-hq.png",icon:"▦"},{title:"الثروة الحيوانية",text:"ثروة حيوانية ومشروعات متكاملة",image:"/assets/invest-livestock-hq.png",icon:"♧"}]},
  culture:{title:"الثقافة",accent:"هوية وإبداع.. نصون تراثنا ونبدع لمستقبلنا",lead:"منصة ثقافية رقمية شاملة تهدف إلى إبراز التراث السوداني الأصيل ودعم المواهب والإبداع في جميع المجالات الثقافية والفنية.",hero:"/assets/culture-hero-hq.png",icon:"◈",tabs:["الفعاليات والأنشطة","الأخبار الثقافية","المكتبة الرقمية","الفنون والأدب","التراث والتاريخ"],stats:[["35","فرقة وجمعية"],["650+","عضو فني"],["120","مبادرة ثقافية"],["85","فعالية ثقافية"]],section:"الفعاليات والأنشطة الثقافية",cards:[{title:"ندوة دور الثقافة",text:"ندوة حول الثقافة في بناء المجتمع",image:"/assets/culture-seminar-hq.png",icon:"♙"},{title:"معرض الفنون",text:"معرض الفنون التشكيلية السنوي",image:"/assets/culture-gallery-hq.png",icon:"▥"},{title:"أمسية شعرية",text:"أمسية للشعراء والشباب",image:"/assets/culture-poetry-hq.png",icon:"♩"},{title:"مهرجان تراث النيل",text:"مهرجان تراثي يحتفي بالهوية",image:"/assets/culture-folk-hq.png",icon:"◈"}]},
};

function Brand({light=false}:{light?:boolean}){return <a href="/" className={`brand ${light?"light":""}`} aria-label="رابطة ولاية نهر النيل الإلكترونية"><span className="brand-mark" aria-hidden><i/><i/><i/><i/></span><span className="brand-copy"><b>رابطة ولاية نهر النيل</b><em>الإلكترونية</em></span></a>}

function Header({active}:{active:PageKey}){
  const [open,setOpen]=useState(false);
  const dark=active==="home"||active==="register";
  return <header className={`topbar ${dark?"dark":""}`}><div className="topbar-inner"><Brand light={dark}/><nav className={open?"open":""}>{nav.map(([href,label])=><a key={href} href={href} className={(href==="/"&&active==="home")||href.includes(active)?"current":""}>{label}</a>)}</nav><div className="header-tools"><button className="search-btn" aria-label="البحث">⌕</button><a className="primary compact" href="/membership">♟&nbsp; تسجيل الدخول</a><button className="mobile-menu" onClick={()=>setOpen(!open)} aria-label="فتح القائمة">{open?"×":"☰"}</button></div></div></header>
}

function Footer(){return <footer className="site-footer"><div className="footer-inner"><div className="footer-brand"><Brand/><p>منصة رقمية شاملة لخدمة أبناء ولاية نهر النيل في الداخل والخارج.</p></div><div><h4>تواصل معنا</h4><p>☎ +249 912 345 678</p><p>✉ info@nilenile.org</p><p>⌖ ولاية نهر النيل - السودان</p></div><div><h4>الدعم والمساعدة</h4><a href="/contact">الأسئلة الشائعة</a><a href="/contact">سياسة الخصوصية</a><a href="/contact">الشروط والأحكام</a></div><div><h4>خدمات الرابطة</h4><a href="/education">التعليم</a><a href="/health">الصحة</a><a href="/investment">الاستثمار</a><a href="/culture">الثقافة</a></div><div><h4>روابط سريعة</h4><a href="/">الرئيسية</a><a href="/membership">عن الرابطة</a><a href="/contact">تواصل معنا</a></div></div><div className="footer-bottom"><span>جميع الحقوق محفوظة © 2026</span><span className="socials">f&nbsp; 𝕏&nbsp; ▶&nbsp; ◎&nbsp; in</span></div></footer>}

function Motion(){useEffect(()=>{const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add("in")}),{threshold:.08});document.querySelectorAll(".motion").forEach(el=>obs.observe(el));return()=>obs.disconnect()},[]);return null}
function SectionTitle({children,mini}:{children:React.ReactNode;mini?:string}){return <div className="section-heading motion">{mini&&<span>{mini}</span>}<h2>{children}</h2></div>}
function Arrow(){return <span aria-hidden>←</span>}

function Home(){
  const services=[{title:"الثقافة",icon:"▥",desc:["التراث","الفعاليات الثقافية","المكتبة الرقمية"],href:"/culture",tone:"cyan"},{title:"التعليم",icon:"▣",desc:["مدرسة نهر النيل","المنح الدراسية","الدورات التدريبية"],href:"/education",tone:"blue"},{title:"الاستثمار",icon:"↗",desc:["الفرص الاستثمارية","المشروعات التنموية","دليل المستثمر"],href:"/investment",tone:"orange"},{title:"السوق السوداني الإلكتروني",icon:"▤",desc:["المنتجات","الخدمات","الشركات"],href:"#market",tone:"purple"},{title:"الخدمات الاجتماعية",icon:"♡",desc:["طلب المساعدة","التكافل الاجتماعي","دعم المرضى"],href:"/social",tone:"green"}];
  return <>
    <section className="home-hero exact-hero"><div className="hero-content motion"><span className="orange-dot">رابطة ولاية</span><h1>نهر النيل الرقمية</h1><h3>منصة رقمية شاملة تربط أبناء ولاية نهر النيل</h3><p>في الداخل والخارج، وتوفر خدمات تواصل وتفاعل وتنمية وتطوير.</p><div className="values"><b>♧<small>تواصل</small></b><b>⌘<small>تفاعل</small></b><b>⚙<small>تنمية</small></b><b>♧<small>تطوير</small></b></div><div className="hero-buttons"><a className="primary" href="#services">استكشف المنصة <Arrow/></a><a className="outline" href="#services">تعرّف على خدماتنا ▦</a></div></div><div className="hero-photo home-visual motion"><img src="/assets/home-hero-hq.png" alt="منظر علوي عالي الدقة لنهر النيل والجسور"/><div className="hero-points"><b><i>♡</i><span>وحدة وتكافل<small>نجمع أبناء الولاية على قلب واحد</small></span></b><b><i>⌘</i><span>خدمات رقمية<small>خدمات متكاملة وسهلة الوصول</small></span></b><b><i>↗</i><span>تنمية مستدامة<small>مبادرات تصنع أثراً حقيقياً</small></span></b><b><i>◎</i><span>وصول عالمي<small>نربط أبناء الولاية حول العالم</small></span></b></div></div></section>
    <section className="metric-bar motion">{[["200+","المبادرات والبرامج","♡"],["35K+","المستفيدون الحاليون","♧"],["120+","الخدمات المقدمة","▦"],["45+","دولة حول العالم","◎"],["850K+","أبناء الولاية حول العالم","⌖"]].map(([n,l,i])=><div key={l}><i>{i}</i><b>{n}</b><span>{l}</span></div>)}</section>
    <section className="join-strip page-width motion"><div className="member-card-css"><Brand light/><strong>عضو في<br/>رابطة ولاية نهر النيل الرقمية</strong><small>0001&nbsp;&nbsp; عضوية</small></div><div><span>انضم الآن إلى</span><h2>رابطة ولاية نهر النيل الرقمية</h2><p>كن جزءاً من أكبر تجمع رقمي لأبناء ولاية نهر النيل واستفد من جميع الخدمات والمبادرات والفرص المتاحة.</p></div><a className="primary join-cta" href="/membership">اضغط هنا<br/>للانضمام الآن <Arrow/></a></section>
    <section id="services" className="section page-width"><SectionTitle mini="ابدأ رحلتك من هنا">خدمات الرابطة الرقمية</SectionTitle><div className="service-columns">{services.map(s=><a className={`service-column motion ${s.tone}`} href={s.href} key={s.title}><i>{s.icon}</i><h3>{s.title}</h3><ul>{s.desc.map(x=><li key={x}>{x}</li>)}</ul><b>الدخول للخدمة <Arrow/></b></a>)}</div></section>
    <section className="investment-banner page-width motion"><img src="/assets/investment-hero-hq.png" alt="فرص الاستثمار في ولاية نهر النيل"/><div className="banner-overlay"><h2>الاستثمار في ولاية نهر النيل</h2><p>فرص استثمارية واعدة في القطاعات الصناعية والزراعية والسكنية</p></div><a href="/investment" className="primary">استكشف الفرص الاستثمارية <Arrow/></a></section>
    <section className="two-features page-width"><article className="feature-panel motion"><div><h2>مدرسة نهر النيل الإلكترونية</h2><h4>تعليم رقمي متكامل من المرحلة الابتدائية حتى الثانوية</h4><ul><li>مناهج تفاعلية وشروحات مرئية</li><li>اختبارات إلكترونية وتقارير دورية</li><li>منصة آمنة وسهلة الاستخدام</li></ul><a className="deep-btn" href="/education">الدخول إلى المدرسة <Arrow/></a></div><img src="/assets/home-school-hq.png" alt="طالبة تستخدم منصة التعليم"/></article><article className="feature-panel motion"><div><h2>معهد نهر النيل الإلكتروني</h2><h4>التدريب المهني والتطوير المستمر</h4><ul><li>دورات مهنية معتمدة</li><li>شهادات احترافية</li><li>لقاءات وتدريب مباشر</li></ul><a className="deep-btn dark" href="/education">الدخول إلى المعهد <Arrow/></a></div><img src="/assets/home-training-hq.png" alt="التدريب المهني عبر الإنترنت"/></article></section>
    <section id="market" className="market-strip page-width motion"><img src="/assets/home-market-hq.png" alt="السوق السوداني الإلكتروني"/><div><span>السوق السوداني الإلكتروني</span><h2>منصة آمنة لبيع وشراء المنتجات والخدمات السودانية</h2><p>ادعم المنتج السوداني وكن جزءاً من تنمية الاقتصاد الوطني.</p></div><a className="deep-btn" href="#">تصفح السوق الآن ▤</a></section>
    <section className="section page-width"><SectionTitle mini="آخر المستجدات">آخر الأخبار والفعاليات</SectionTitle><div className="news-grid">{["مشروع التنمية المستدامة","دورات تدريبية متخصصة","مبادرة دعم المدارس","ملتقى شباب نهر النيل 2025"].map((x,i)=><article className="news-card motion" key={x}><img src={["/assets/invest-livestock-hq.png","/assets/culture-seminar-hq.png","/assets/social-education-hq.png","/assets/culture-poetry-hq.png"][i]} alt=""/><div><time>مايو 2025</time><h3>{x}</h3><p>خبر جديد من فعاليات ومبادرات رابطة ولاية نهر النيل.</p><a href="/culture">اقرأ المزيد <Arrow/></a></div></article>)}</div></section>
  </>
}

function PortalHero({type}:{type:PortalKey}){const p=info[type];return <><section className={`portal-hero portal-${type}`}><div className="portal-copy motion"><h1>{p.title}</h1><h2>{p.accent}</h2><p>{p.lead}</p></div><div className="portal-image motion"><img src={p.hero} alt={p.title}/></div>{["education","investment","culture"].includes(type)&&<aside className="portal-side motion"><h3>{p.icon}&nbsp; خدمات {p.title}</h3>{p.tabs.map((t,i)=><a key={t} className={i===0?"selected":""} href="#services">{t}<span>⌃</span></a>)}</aside>}</section><section className="portal-features motion">{(type==="health"?["في خدمتكم أينما كنتم","متاحة إلكترونياً","خدمة سريعة","موثوقة وآمنة"]:type==="social"?["حالات إنسانية","تواصل مباشر","استشارة اجتماعية","برامج ومبادرات","دعم المحتاجين"]:["جودة وتميز","دعم شامل","محتوى متخصص","تعلّم مرن"]).map((x,i)=><div key={x}><i>{["◎","▣","◷","♢","♡"][i]}</i><b>{x}</b><span>خدمة رقمية متكاملة</span></div>)}</section></>}

function PortalPage({type}:{type:PortalKey}){const p=info[type];return <><PortalHero type={type}/><section className="stat-ribbon page-width motion">{p.stats.map(([n,l],i)=><div key={l}><i>{["♧","⌂","▦","↗"][i]}</i><b>{n}</b><span>{l}</span></div>)}</section><section id="services" className="section page-width"><SectionTitle mini="خدمات متكاملة بين يديك">{p.section}</SectionTitle><div className={`visual-card-grid ${type==="health"?"three-primary":""}`}>{p.cards.map((c,i)=><article className={`visual-card motion ${i===3&&type==="health"?"wide-health":""}`} key={c.title}><img src={c.image} alt={c.title}/><div><i>{c.icon}</i><h3>{c.title}</h3><p>{c.text}</p><ul><li>خدمة سهلة وسريعة</li><li>متابعة ودعم مستمر</li><li>خصوصية وأمان</li></ul><a href="/contact" className="card-action">{type==="social"?"ساهم الآن":"معرفة المزيد"} <Arrow/></a></div></article>)}</div></section>{type==="education"&&<EducationExtras/>}{type==="investment"&&<InvestmentExtras/>}{type==="culture"&&<CultureExtras/>}{type==="social"&&<SocialExtras/>}{type==="health"&&<HealthExtras/>}<SupportBar/></>}

function EducationExtras(){return <><section className="library-band page-width motion"><div><span>المكتبة الرقمية</span><h2>مصادر تعليمية موثوقة ومتنوعة</h2><div className="library-items"><b>▥ 2,500+ كتاب</b><b>▣ 1,200+ بحث ومقال</b><b>▶ 800+ فيديو</b><b>▤ 3,000+ ملف</b></div></div><img src="/assets/education-hero-hq.png" alt="المكتبة الرقمية"/></section><section className="compact-panels page-width"><article><h3>الأخبار التعليمية</h3>{["إطلاق منصة مدرسة نهر النيل","بدء التسجيل في المنح","نتائج الاختبارات الفصلية"].map(x=><p key={x}>◫ {x}<small>مايو 2025</small></p>)}</article><article><h3>الفعاليات القادمة</h3>{["ورشة مهارات المستقبل","ندوة التعليم الرقمي","ملتقى الطلاب والمعلمين"].map(x=><p key={x}>◷ {x}<small>قريباً</small></p>)}</article></section></>}
function InvestmentExtras(){return <><section className="solar-banner page-width motion"><img src="/assets/investment-solar-hq.png" alt="الطاقة الشمسية"/><div><h2>استثمر في الطاقة الشمسية</h2><p>مشروع محطة طاقة شمسية بقدرة 50 ميجاوات</p><a className="primary" href="/contact">اعرف المزيد</a></div></section><section className="compact-panels page-width"><article><h3>مزايا المستثمر</h3><div className="icon-row"><b>شبكة بنية تحتية</b><b>إجراءات ميسرة</b><b>دعم فني وإداري</b><b>تسويق مضمون</b></div></article><article><h3>قصة نجاح</h3><img className="mini-story" src="/assets/invest-industry-hq.png" alt="مشروع استثماري ناجح"/><p>مشروع دواجن الدامر.. من فكرة صغيرة إلى قصة نجاح كبيرة.</p></article></section></>}
function CultureExtras(){return <><section className="compact-panels page-width"><article><h3>المكتبة الرقمية</h3><div className="culture-library"><img src="/assets/culture-hero-hq.png" alt="كتب وتراث"/><div><h2>آلاف الكتب والمراجع الثقافية</h2><p>كتب التراث السوداني، الدراسات والبحوث، المجلات الثقافية والكتب المصورة.</p><a className="primary" href="#">استكشف المكتبة</a></div></div></article><article><h3>المسابقات والجوائز</h3>{["مسابقة الشعر السنوية","جائزة الإبداع الفني","جائزة التصوير الضوئي"].map(x=><p key={x}>♕ {x}<small>مايو 2025</small></p>)}</article></section><section className="compact-panels page-width"><article><h3>الفرق والجمعيات الثقافية</h3><div className="icon-row"><b>جمعية الخط العربي</b><b>جمعية المسرح</b><b>نادي الأدب</b><b>فرقة نهر النيل</b></div></article><article><h3>شارك محتواك الثقافي</h3><p>لديك موهبة أو محتوى ثقافي؟ شاركه مع مجتمعنا.</p><a className="primary" href="/contact">أرسل محتواك</a></article></section></>}
function SocialExtras(){return <section className="social-counts page-width motion">{[["120+","متطوع نشط"],["320+","طالب مستفيد"],["650+","فرصة دعم"],["1,850+","حالة إنسانية"],["3,250+","أسرة مستفيدة"],["12,680+","مستفيد"]].map(([n,l])=><div key={l}><i>♧</i><b>{n}</b><span>{l}</span></div>)}</section>}
function HealthExtras(){return <><section className="health-help page-width motion"><div><h2>طلب المساعدة والتواصل مع الرابطة</h2><p>نحن معك في الحالات الصحية والإنسانية</p></div><div className="health-actions"><b>♡ رفع حالة لطلب طبي</b><b>♧ طلب مساعدة صحية عاجلة</b><b>☏ التواصل المباشر</b><b>▤ متابعة حالة</b></div><a className="primary" href="/contact">إرسال طلب المساعدة</a></section><section className="health-tips page-width"><SectionTitle>نصائح صحية</SectionTitle><div>{["متابعة دورية لحالتك المرضية","تغذية متوازنة لجسم أكثر صحة","المشي 30 دقيقة يومياً","اشرب الماء لصحة أفضل"].map((x,i)=><b className="motion" key={x}><i>{["♡","♧","♟","◉"][i]}</i>{x}</b>)}</div></section></>}
function SupportBar(){return <section className="support-bar page-width motion"><i>☏</i><div><h2>نحن هنا لمساعدتك</h2><p>فريق الدعم جاهز للرد على استفسارك وتقديم المساعدة.</p></div><div><b>واتساب</b><span>+249 912 345 678</span></div><div><b>البريد الإلكتروني</b><span>info@nilenile.org</span></div><a className="outline light" href="/contact">تواصل معنا <Arrow/></a></section>}

const plans=[{name:"الباقة الأساسية",price:"50",tone:"bronze",features:["الدخول إلى منصة الرابطة","الاشتراك في النشرة الدورية","دعوات عامة للفعاليات","المشاركة في الاستبيانات","تحديثات دورية عن الأنشطة"]},{name:"الباقة المميزة",price:"100",tone:"orange",features:["جميع مزايا الباقة الأساسية","الأولوية في التسجيل","خصومات حصرية لدى شركائنا","الوصول إلى المحتوى الحصري","دعوات خاصة للندوات"]},{name:"الباقة الداعمة",price:"200",tone:"dark",features:["جميع مزايا الباقتين السابقتين","دعم مباشر لمشاريع الرابطة","شهادة شكر وتقدير إلكترونية","دعوات VIP للفعاليات الكبرى","لقاءات خاصة مع القيادات"]}];

function Membership(){const [selected,setSelected]=useState(1);return <><div className="membership-pricing-logo"><Brand/></div><section className="membership-hero exact-hero"><div className="hero-photo motion"><img src="/assets/membership-hero-hq.png" alt="باقات عضوية رابطة ولاية نهر النيل"/></div><div className="hero-content motion"><h1>باقات العضوية</h1><h2>الاشتراكات السنوية</h2><p>اختر الباقة التي تناسبك واستمتع بمزايا حصرية تدعمك وتخدم أبناء ولايتك.</p></div><div className="membership-card-image motion"><div className="membership-card-preview"><Brand light/><span className="card-chip">NRN</span><strong>بطاقة عضوية إلكترونية</strong><small>رابطة ولاية نهر النيل</small><div><b>عضو معتمد</b><em>0001</em></div></div></div></section><section className="member-benefits page-width motion">{[["♧","مجتمع متفاعل","تواصل وتعاون مع أبناء الولاية"],["♢","موثوق وآمن","حماية بياناتك وخصوصيتك"],["♕","مزايا حصرية","خدمات وعروض خاصة"],["↗","مساهمة مؤثرة","شارك في بناء مستقبل الولاية"]].map(([i,t,d])=><div key={t}><i>{i}</i><h3>{t}</h3><p>{d}</p></div>)}</section><section className="section page-width"><div className="plans-grid">{plans.map((p,i)=><article key={p.name} onClick={()=>setSelected(i)} className={`price-card motion ${p.tone} ${selected===i?"chosen":""}`}>{i===1&&<span className="most">الأكثر اختياراً</span>}<h2>{p.name}</h2><strong>{p.price}</strong><small>ريال سنوياً</small><h4>المميزات</h4><ul>{p.features.map(f=><li key={f}>✓ {f}</li>)}</ul><a className="plan-button" href={`/register?plan=${i}`}>اختر هذه الباقة</a></article>)}</div></section><section className="all-benefits page-width motion"><SectionTitle>مزايا لجميع الأعضاء</SectionTitle><div>{["تأثير مستدام","خدمات وعروض حصرية","محتوى ومعلومات حصرية","فرص تعليم وتدريب","شبكة علاقات واسعة"].map(x=><b key={x}>♧<small>{x}</small></b>)}</div></section><SupportBar/></>}

function Register(){const onSubmit=(e:FormEvent)=>{e.preventDefault();location.href="/photo"};return <><section className="register-intro"><div className="motion"><h1>سجل عضويتك</h1><h2>في رابطة ولاية نهر النيل الإلكترونية</h2><p>انضم إلى أكبر قاعدة بيانات موثوقة لأبناء ولاية نهر النيل.</p><div className="mini-stats"><b>12,850+<small>أعضاء مسجلون</small></b><b>48+<small>دول العالم</small></b><b>320+<small>مدينة</small></b></div></div><img className="motion" src="/assets/membership-hero-hq.png" alt="التسجيل في عضوية الرابطة"/></section><section className="form-shell page-width"><SectionTitle mini="يرجى تعبئة البيانات التالية بدقة">نموذج تسجيل العضوية</SectionTitle><form className="mega-form" onSubmit={onSubmit}>{[{title:"البيانات الشخصية",icon:"♙",fields:["الاسم الرباعي","الاسم وفق الجواز","تاريخ الميلاد","الجنسية"]},{title:"بيانات الإقامة",icon:"⌖",fields:["الدولة","المدينة","الحي","رقم الجوال"]},{title:"بيانات السودان",icon:"▣",fields:["الولاية","المحلية","الوحدة الإدارية","القرية / الحي"]},{title:"المؤهل العلمي",icon:"✦",fields:["المرحلة التعليمية","التخصص","اسم الجامعة","سنة التخرج"]},{title:"بيانات الأسرة",icon:"♧",fields:["الحالة الاجتماعية","عدد أفراد الأسرة","أعمار الأبناء","بيانات إضافية"]},{title:"البيانات المهنية",icon:"▦",fields:["المجال المهني","المسمى الوظيفي","سنوات الخبرة","جهة العمل"]},{title:"الحالة الصحية",icon:"♡",fields:["هل لديك مرض مزمن؟","نوع الحالة","التوضيح","ملاحظات"]},{title:"التواصل",icon:"☏",fields:["رقم بديل","واتساب","البريد الإلكتروني","حساب التواصل"]}].map(g=><fieldset key={g.title}><legend>{g.icon} {g.title}</legend>{g.fields.map((f,i)=><label key={f}>{f}{i===0&&<em>*</em>}<input required={i===0} placeholder={`أدخل ${f}`}/></label>)}</fieldset>)}<fieldset className="interests"><legend>الاهتمامات</legend><div>{["التعليم","المباشر","ريادة الأعمال","المرأة","الاستثمار","الثقافة","الاستشارات","اليوم العام"].map(x=><label key={x}><input type="checkbox"/>{x}</label>)}</div></fieldset><label className="privacy"><input required type="checkbox"/> أوافق على الشروط والأحكام وسياسة الخصوصية.</label><button className="primary register-submit">سجل الآن <Arrow/></button></form></section></>}

function PhotoUpload(){const input=useRef<HTMLInputElement>(null);const [preview,setPreview]=useState<string>();const pick=(file?:File)=>{if(file)setPreview(URL.createObjectURL(file))};return <MembershipStep><SectionTitle mini="يرجى إرفاق صورة شخصية حديثة وواضحة">إرفاق صورة شخصية<br/><span className="orange-text">لإصدار البطاقة الإلكترونية</span></SectionTitle><div className="portrait-box">{preview?<img src={preview} alt="معاينة الصورة"/>:<div className="silhouette">♟</div>}<b>معاينة الصورة</b><p>تأكد من وضوح الصورة قبل رفعها<br/>ستستخدم لطباعة البطاقة الإلكترونية</p></div><SectionTitle>اختر طريقة الإرفاق</SectionTitle><div className="upload-ways"><button onClick={()=>input.current?.click()}>▤<b>إرفاق ملف</b><span>اختر صورة من جهازك</span></button><button className="active" onClick={()=>input.current?.click()}>▣<b>التقاط صورة</b><span>باستخدام الكاميرا</span></button><button>◒<b>التقاط من الاستديو</b><span>باستخدام إضاءة الاستديو</span></button></div><input ref={input} hidden type="file" accept="image/*" onChange={e=>pick(e.target.files?.[0])}/><div className="photo-rules"><h2>♢ شروط الصورة</h2><ul><li>صورة حديثة وواضحة</li><li>خلفية بيضاء أو فاتحة</li><li>إظهار الوجه بوضوح</li><li>بدون نظارات شمسية</li><li>بدون فلاتر أو تعديلات</li></ul><p>الصيغ المدعومة: JPG, JPEG, PNG<br/>الحد الأقصى للحجم: 2MB</p></div><a className="primary step-next" href="/payment">المتابعة إلى السداد <Arrow/></a></MembershipStep>}
function Payment(){return <MembershipStep><SectionTitle mini="اختر طريقة السداد المناسبة وارفع المستندات المطلوبة">خيارات السداد</SectionTitle><div className="payment-options">{[{n:"01",i:"▥",t:"إرفاق ما يعادلها ببنكك",d:"قم بإيداع المبلغ في حساب الرابطة وارفع ما يعادلها من كشف الحساب"},{n:"02",i:"▤",t:"إرفاق سند السداد",d:"قم برفع صورة أو ملف سند السداد الرسمي الصادر من الجهة"},{n:"03",i:"⌘",t:"إرفاق التحويل البنكي",d:"قم برفع صورة أو ملف إثبات التحويل البنكي"}].map(x=><article key={x.n}><b>{x.n}</b><i>{x.i}</i><div><h2>{x.t}</h2><p>{x.d}</p></div><label>⇧<strong>اختر ملف أو اسحب وأفلت</strong><small>JPG, PNG, PDF (الحد الأقصى 5MB)</small><input type="file" hidden/></label></article>)}<article className="visa"><b>04</b><i>VISA</i><div><h2>السداد فيزا</h2><p>ادفع الآن مباشرة باستخدام بطاقتك البنكية عبر فيزا</p></div><a className="primary" href="/success">ادفع عبر فيزا&nbsp; VISA</a></article></div><div className="notice">ⓘ سيتم التحقق من مستندات السداد وتأكيدها خلال 24 ساعة عمل، وسيصلك إشعار بعد اعتماد السداد وتفعيل عضويتك.</div><a className="primary step-next" href="/success">إرسال المستندات <Arrow/></a></MembershipStep>}
function Success(){return <MembershipStep><div className="success-view"><div className="checkmark">✓</div><h1>مبروك</h1><h2>أنت الآن عضو<br/>في رابطة ولاية نهر النيل الإلكترونية</h2><div className="member-number"><i>♙</i><h3>رقم العضوية</h3><strong>NRN-2026-000123</strong><hr/><h3>الباركود</h3><div className="barcode"/><small>N R N 2 0 2 6 0 0 0 1 2 3</small></div><div className="thanks"><i>♢</i><div><h2>شكراً لانضمامك إلينا</h2><p>معاً نبني مجتمعاً رقمياً قوياً ومتكافلاً لخدمة أبناء الولاية.</p><b>وحدتنا.. قوتنا&nbsp;&nbsp; ومستقبلنا.. مسؤوليتنا</b></div></div><a className="primary" href="/">العودة إلى الرئيسية</a></div></MembershipStep>}
function MembershipStep({children}:{children:React.ReactNode}){return <main className="membership-step"><Brand/>{children}</main>}

function Contact(){const [sent,setSent]=useState(false);const submit=(e:FormEvent)=>{e.preventDefault();setSent(true)};return <><section className="contact-hero exact-hero"><div className="hero-content motion"><h1>تواصل معنا</h1><h2>نحن هنا لخدمتكم</h2><p>نسعد بتواصلكم واستقبال استفساراتكم ومقترحاتكم وشكاواكم، فريقنا جاهز للرد عليكم وتقديم الدعم في أسرع وقت ممكن.</p></div><div className="hero-photo motion"><img src="/assets/contact-hero-hq.png" alt="تواصل معنا"/></div></section><section className="member-benefits page-width motion">{[["♧","نحن معكم","نتواصل معكم بما يسهم في تطوير خدماتنا"],["◎","خدمتكم أينما كنتم","ندعمكم من داخل وخارج الولاية"],["♢","خصوصية وأمان","نحافظ على سرية معلوماتكم"],["◷","استجابة سريعة","نرد على رسائلكم في أسرع وقت"],["☏","فريق متخصص","فريق دعم متكامل لخدمتكم"]].map(([i,t,d])=><div key={t}><i>{i}</i><h3>{t}</h3><p>{d}</p></div>)}</section><section className="contact-layout page-width"><aside><h2>طرق التواصل</h2>{[["◉","واتساب","+249 912 345 678"],["☏","اتصال هاتفي","+249 123 456 789"],["✉","البريد الإلكتروني","info@nilenile.org"],["⌖","العنوان","ولاية نهر النيل - السودان"],["◷","ساعات العمل","الأحد إلى الخميس · 9ص - 5م"]].map(([i,t,d])=><div key={t}><i>{i}</i><span><b>{t}</b>{d}</span></div>)}</aside><form onSubmit={submit}><h2>أرسل لنا رسالة</h2>{sent?<div className="sent"><i>✓</i><h2>تم إرسال رسالتك بنجاح</h2><p>سنتواصل معك في أقرب وقت.</p></div>:<><div className="form-row"><label>الاسم الكامل *<input required/></label><label>البريد الإلكتروني *<input required type="email"/></label></div><label>رقم الجوال<input type="tel"/></label><label>اختر نوع الرسالة *<select required><option>استفسار عام</option><option>شكوى</option><option>اقتراح</option><option>دعم فني</option></select></label><label>نص الرسالة *<textarea required rows={5}/></label><label className="file-field">⇧ إرفاق ملف (اختياري)<input type="file"/></label><button className="primary">إرسال الرسالة <Arrow/></button></>}</form></section><section className="section page-width"><SectionTitle>أسئلة شائعة</SectionTitle><div className="faq-cards">{[["الخدمات والبرامج","تفاصيل عن خدماتنا وبرامجنا"],["الدعم الفني","المساعدة في استخدام المنصة"],["العضوية والدفع","الاستفسار عن العضوية وطرق الدفع"],["الشكاوى والمقترحات","نستقبل شكاواكم ومقترحاتكم"],["الاستفسارات العامة","إجابات على أكثر الأسئلة الشائعة"]].map(([t,d])=><a href="#" key={t}><i>◫</i><b>{t}</b><span>{d}</span></a>)}</div></section><section className="newsletter page-width motion"><div><h2>كن على تواصل دائم</h2><p>اشترك في نشرتنا البريدية ليصلك كل جديد من أخبار الرابطة والفعاليات والخدمات.</p></div><form><input type="email" placeholder="البريد الإلكتروني"/><button className="primary">اشترك الآن</button></form></section></>}

export default function NileSite({page}:{page:string}){const active=routeMap[page]||"home";const hideHeader=["membership","photo","payment","success"].includes(active);const hideFooter=["photo","payment","success"].includes(active);return <div dir="rtl"><Motion/>{!hideHeader&&<Header active={active}/>}<main>{active==="home"?<Home/>:active==="membership"?<Membership/>:active==="register"?<Register/>:active==="photo"?<PhotoUpload/>:active==="payment"?<Payment/>:active==="success"?<Success/>:active==="contact"?<Contact/>:<PortalPage type={active}/>}</main>{!hideFooter&&<Footer/>}</div>}
