ALTER TABLE news
  ADD COLUMN IF NOT EXISTS author_name text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS author_image_url text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS read_time int NOT NULL DEFAULT 0;

ALTER TABLE events
  ADD COLUMN IF NOT EXISTS author_name text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS author_image_url text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS organizer text NOT NULL DEFAULT '';
